include conf/machine/stm32mp25-mx.conf

MACHINEOVERRIDES =. "stm32mp25-mx"

BOOTSCHEME_LABELS += "optee"

BOOTDEVICE_LABELS += "sdcard"

#CUBEMX_DTB name of CubeMX generated device tree files, without file extension (e.g. stm32mp135f-<ProjectName>-mx)
#CUBEMX_PROJECT path of CubeMX generated device tree files relative to layer path folder (e.g. mx/<ProjectPath>)
#CUBEMX_PROJECT_NAME name of CubeMX project (e.g. <ProjectName>)

CUBEMX_PROJECT_NAME = "firmware"
CUBEMX_PROJECT = "mx/Watermelon-Wine-1A/watermelon-wine-os/cubemx"
CUBEMX_DTB = "stm32mp257f-${CUBEMX_PROJECT_NAME}-mx"
