# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-watermelon-wine"
BBFILE_PATTERN_meta-watermelon-wine = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-watermelon-wine = "6"

LAYERDEPENDS_meta-watermelon-wine = "stm-st-stm32mp-mx"
LAYERSERIES_COMPAT_meta-watermelon-wine = "scarthgap"
